### ISSUE TITLE
Clash 报错

### ISSUE THREAD

**Issue by lzyywsgl** [anaer/Sub#10]
![image](https://user-images.githubusercontent.com/33905172/221490463-327185cc-f14b-4f1d-ba3c-275f5c55c970.png)
Clash V 0.19.0

**Comment by anaer** [comment]
1. 如果规则文件获取都报错, 可以参考这个issue [initial rule provider reject error:context deadline exceeded](https://github.com/Loyalsoldier/clash-rules/issues/92)
2. 如果仅是这个规则拉取报错, 可以到Providers菜单中单独刷新
