### ISSUE TITLE
代理网站失效了，下载配置文件报错。

### ISSUE THREAD

**Issue by githubwjh** [anaer/Sub#11]
下载配置文件报错这行：
https://ghproxy.net/https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Clash/Advertising/Advertising_Classical.yaml

原因是 https://ghproxy.net 失效不能访问，代理下载失败。手动编辑改成其他的代理网站测正常。

**Comment by anaer** [comment]
谢谢反馈 已修改地址
