### ISSUE TITLE
请教大神，为什么在clash for Android上不可使用？

### ISSUE THREAD

**Issue by Poseidon965807** [anaer/Sub#13]

**Comment by anaer** [comment]
如果是提示rule—set的问题, 需要使用premium版本

**Comment by wujinjun-MC** [comment]
password存在问题，float64类型不支持
![Screenshot_20230605_225057](https://github.com/anaer/Sub/assets/89054683/2b09ef71-f3af-4e99-8c28-4fa35baf6750)

**Comment by anaer** [comment]
float64类型已做处理
