### ISSUE TITLE
这是啥情况

### ISSUE THREAD

**Issue by yenaitiancai** [anaer/Sub#14]
![Screenshot_20230924_004045_com.github.kr328.clash.jpg](https://github.com/anaer/Sub/assets/66541129/497db496-e0b2-4bd0-8161-4d42b9f3f642)

![Screenshot_20230924_003945_com.github.kr328.clash.jpg](https://github.com/anaer/Sub/assets/66541129/40243030-329c-470b-b357-0a8f55e620a2)

是我用的不对吗

**Comment by anaer** [comment]
因为没用这个Android客户端 所以不太确定, 可能是下载规则文件慢吧
