### ISSUE TITLE
无法切换到此配置文件

### ISSUE THREAD

**Issue by wenvane001** [anaer/Sub#18]
![360截图20240202154410906](https://github.com/anaer/Sub/assets/32939567/c4480f0b-81c3-4de2-8059-be3a4849eb8c)
最近电脑更新一直提示这个错误，Clash.for.Windows-0.20.39-win

**Comment by anaer** [comment]
多谢反馈，已改回默认的负载均衡策略

**Comment by wenvane001** [comment]
刚更新后，提示下面问题
![111](https://github.com/anaer/Sub/assets/32939567/ff245a9e-4540-40c8-880e-01dc3c533e52)

**Comment by anaer** [comment]
规则文件下载失败了，加了个国内直连的链接，可以试下
https://cdn.jsdelivr.net/gh/anaer/Sub@main/clash.cn.yaml
