### ISSUE TITLE
clash for android 更新配置失败

### ISSUE THREAD

**Issue by RunZH** [anaer/Sub#22]
yaml unmarshal error:
line 103 cannot unmarshal !!seq into string

**Comment by YaoLiMuMu** [comment]
Identical error on clash for Android and Linux
sub url: https://cdn.jsdelivr.us/gh/anaer/Sub@main/clash.yaml

**Comment by YaoLiMuMu** [comment]
<pre><font color="#555753">09:03:43</font> <font color="#CC0000">FTL</font> [Config] parse config failed <font color="#CC0000">error=rules[3] [GEOSITE,github,GITHUB] error: unsupported rule type GEOSITE</font>
</pre>
error on clash for Android and Linux

**Comment by anaer** [comment]
更新了下, 使用最新的看下

**Comment by YaoLiMuMu** [comment]
@anaer 我重新更新了下, 现在linux端是可以了, 但是手机上面不行, 还是是rules段的数据引起的.
区别应该是 不同订阅源的文本应该不相同吧, 
我wget了下面两个网址, yaml文本不相同;
https://cdn.jsdelivr.us/gh/anaer/Sub@main/clash.yaml
https://anaer.github.io/Sub/clash.yaml

**Comment by anaer** [comment]
cdn源有的有缓存的, 可以换个源看下
