### ISSUE TITLE
无法连接Telegram

### ISSUE THREAD

**Issue by HashLiver** [anaer/Sub#8]
改版后的规则很不好用，Telegram ip段居然是直连的。

Clash for Android的日志：

`[TCP] dial DIRECT to 91.108.56.137:443 error: dial tcp4 91.108.56.137:443: i/o timeout`

**Comment by anaer** [comment]
应该是之前默认的Script模式，该模式主要自用调试，所以没配啥规则, 
现在已调整为默认Rule模式，该模式使用三方整理的规则  应该比较全面, 本机试了下该模式 访问Telegram没问题的
