### ISSUE TITLE
clashx 订阅报错。Remote Config Format Error: rules[0] [RULE-SET,applications,DIRECT] error: unsupported rule type RULE-SET

### ISSUE THREAD

**Issue by timyeung** [anaer/Sub#9]
Remote Config Format Error: rules[0] [RULE-SET,applications,DIRECT] error: unsupported rule type RULE-SET

**Comment by anaer** [comment]
检查下安装的clashx的版本看看， 看[Release Note](https://github.com/yichengchen/clashX/releases) , ClashX Pro 1.91.1以上是支持rule set的

**Comment by wiphone-wu** [comment]
你好，我是使用clash for android 2.5.12.foss版报的错。不是clash x。请问是需要更新clash for android吗，谢谢

从 Windows 版邮件<https://go.microsoft.com/fwlink/?LinkId=550986>发送

发件人: ***@***.***>
发送时间: 2023年2月27日 12:45
收件人: ***@***.***>
抄送: ***@***.***>
主题: Re: [anaer/Sub] clashx 订阅报错。Remote Config Format Error: rules[0] [RULE-SET,applications,DIRECT] error: unsupported rule type RULE-SET (Issue #9)


检查下安装的clashx的版本看看， 看Release Note<https://github.com/yichengchen/clashX/releases> , ClashX Pro 1.91.1以上是支持rule set的

―

**Comment by anaer** [comment]
看了下ClashForAndroid的issue [[BUG] error: unsupported rule type RULE-SET](https://github.com/Kr328/ClashForAndroid/issues/1751), 说是foss版本不支持, 可以试下premium版本

**Comment by wiphone-wu** [comment]
换成premium版本就可以了，谢谢

从 Windows 版邮件<https://go.microsoft.com/fwlink/?LinkId=550986>发送

发件人: ***@***.***>
发送时间: 2023年2月27日 17:54
收件人: ***@***.***>
抄送: ***@***.***>; ***@***.***>
主题: Re: [anaer/Sub] clashx 订阅报错。Remote Config Format Error: rules[0] [RULE-SET,applications,DIRECT] error: unsupported rule type RULE-SET (Issue #9)


看了下ClashForAndroid的issue [BUG] error: unsupported rule type RULE-SET<https://github.com/Kr328/ClashForAndroid/issues/1751>, 说是foss版本不支持, 可以试下premium版本

―
